#!/bin/sh
#
# If the ./configure script is missing, you can run this script to create it
#

if ! test -e config; then
    mkdir config
fi

if ! test -e config/ltmain.sh; then
    if test -e /usr/share/libtool/config/ltmain.sh; then
        cp /usr/share/libtool/config/ltmain.sh config
        cp /usr/share/libtool/config/config.guess \
           /usr/share/libtool/config/config.sub .
    else
        cp /usr/share/libtool/ltmain.sh config
        cp /usr/share/libtool/config.guess \
           /usr/share/libtool/config.sub .
    fi
fi

aclocal \
&& automake --gnu --add-missing --copy \
&& autoconf
rm -rf autom4te.cache
